### ISSUE TITLE
Set pinned weblinks

### ISSUE THREAD

**Issue by CelesVersia** [MicrosoftDocs/IntuneDocs.es-es#25]
Its posible when creating a weblink set a default Browser?

Our interest is create 2 weblinks and each weblink will be opened whit different browsers... i dont know if that is posible.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2020a2db-99bb-0cf0-830f-806ce531a39a
* Version Independent ID: 938449a4-68a0-8aef-3699-f9509e888bf5
* Content: [Configuración de la aplicación Managed Home Screen de Microsoft - Microsoft Intune](https://docs.microsoft.com/es-es/intune/app-configuration-managed-home-screen-app#feedback)
* Content Source: [intune/app-configuration-managed-home-screen-app.md](https://github.com/MicrosoftDocs/IntuneDocs.es-es/blob/live/intune/app-configuration-managed-home-screen-app.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by CeciAc** [comment]
Hello, @CelesVersia

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
